package com.thaumaturzy.b2b;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ImmigrationDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(generator = "IMMIGRATIONDETAILS_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "IMMIGRATIONDETAILS_ID_GENERATOR", sequenceName = "IMMIGRATIONDETAILS_ID_SEQ")
    private java.lang.Long id;

    public ImmigrationDetails() {
    }
    
    public ImmigrationDetails(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}